spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    defer-datasource-initialization: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'false'

logging:
  level:
    br.wendel.mb7.challenge: DEBUG
